on:
  pull_request:
  push:
    paths:
      - "**.nix"
      - "**.rs"
      - "**.lock"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix develop -c rustc --version
    - run: nix run
