name: ci

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
  push:
    paths:
      - ".github/workflows/*.yml"
      - "**.lock"
      - "**.nix"
      - "**.rs"
      - "**.toml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main 
      - run: nix develop -c cargo --version
      - run: nix develop -c rustc --version
      - run: nix run
